### ISSUE TITLE
Bug: Detuned Samples

### ISSUE THREAD

**Issue by Micasddsa** [paandorasbox/paandorasbox.github.io#2]
(Disclaimer: I do know that this is beta but just thought to make this bug report in case if someone missed this and just general bug reporting.)
The Title Says It All, Some Instrument's Samples are detuned.

Here is an Example Song that has all the instruments that are detuned, Channel 7 is a Beepbox Synth and a example of what the melody should sound like and Channel 8 Is the bass line (idk why I included it but it might be helpful). 
Recommended To Turn On The Enable Channel Muting Preference.
https://tinyurl.com/y5rxalha

**Comment by Micasddsa** [comment]
Removing this link because now it's fixed and you don't need these.

**Comment by paandorasbox** [comment]
this hopefully should all be fixed now (let me know if I missed any of them)
