### ISSUE TITLE
Bug: Sampled Instruments Looping Problem

### ISSUE THREAD

**Issue by Micasddsa** [paandorasbox/paandorasbox.github.io#4]
(Disclaimer: I do know that this is beta but just thought to make this bug report in case if someone missed this and just general bug reporting.)
The Sampled Instruments Either Clicking Or Repeating itself. 

Here is a demo song, The First Instrument Loops itself and the Second Clicks.
https://tinyurl.com/y5yfqcp6

Possible Solution: Somehow make a way to modify loop points so at least for the first instrument to loop and the end so It sounds like it's silent (or just remove looping.) and the second is to modify loop points to make it sound more like looped.

**Comment by ghost** [comment]
I may get around to fixing this sometime soon

**Comment by ghost** [comment]
you're probably already aware of this, but [ultrabox](https://ultraabox.github.io/) has custom sampling, loop controls, and support for old paandorasbox samples, so
