### ISSUE TITLE
Bug: "Sonic 3 Snare" is actually the Sonic 1 Snare. (Minnor Issue)

### ISSUE THREAD

**Issue by Micasddsa** [paandorasbox/paandorasbox.github.io#6]
The name says it all. It's a minor issue sure but correcting the name would stop confusion.

Example:
What's in Pandora's Box: https://tinyurl.com/y377kt3p
What's it's supposed to sound like: https://youtu.be/duTkTwaXAW0 (Yes i know it's not just the drums it has the bass but it's good for an example.)

**Comment by ghost** [comment]
Fixed
